@extends('admin.main')
@section('content')
    <product_form
        main_route="{{route('home')}}"
        :categories_options="{{$categories_options}}"
        :colors_options="{{$colors_options}}"
        form_type="create"></product_form>
@endsection
@section('scripts')
@endsection
